###

GET http://localhost:8080/api/gebruikers
Accept: application/json

###

GET http://localhost:8080/api/gebruikers/1
Accept: application/json

###

POST http://localhost:8080/api/gebruikers
Content-Type: application/json
Accept: application/json

{
  "postalCode": "2689LO",
  "firstName": "Jan",
  "middleName": "van",
  "lastName": "Ronde",
  "username": "ditisjan",
  "password": "waaromookniet",
  "address": "Straat 123",
  "email": "janzijnmain@mail.com"
}

###
