###

GET http://localhost:8080/api/gebruikers
Accept: application/json

###

GET http://localhost:8080/api/gebruikers/1
Accept: application/json

###

POST http://localhost:8080/api/gebruikers
Content-Type: application/json
Accept: application/json

{
  "postalCode": "2322HU",
  "firstName": "Niels",
  "middleName": "der",
  "lastName": "Vierkant",
  "username": "ditisniels",
  "password": "waaromookniet123",
  "address": "Straat 12",
  "email": "nielszijnmain@mail.com"
}

###
