###

GET http://localhost:8080/api/gebruikers
Accept: application/json

###

GET http://localhost:8080/api/gebruikers/1
Accept: application/json

###

POST http://localhost:8080/api/gebruikers
Content-Type: application/json
Accept: application/json

{
  "postalcode": "2689LO",
  "firstname": "Jan",
  "middlename": "van",
  "lastname": "Ronde",
  "username": "ditisjan123",
  "password": "waaromookniet",
  "address": "Straat 123",
  "email": "janzijnmain@mail.com"
}

###
